const testeSQLPivotRollup = [""
+ "SELECT																																																																																																																			"
+ "[Mercado._rac] as Mercado																																																																																																														"
+ ", Tipo_Problema_rac as [Tipo do Problema]																																																																																																										"
+ ", Nm_Manifestante_rac as [Manifestante]																																																																																																											"
+ ", count(Rac_rac) as [Nº RAC]																																																																																																														"
+ "INTO #RESULTADO 																																																																																																																	"
+ "FROM [v_base_rac]																																																																																																																"
+ "WHERE Mercado_rac = 'ME'																																																																																																															"
+ "and year(data_rac) = (select year(data) as data from v_maiorData)																																																																																																				"
+ "and month(data_rac) = (select month(data) as data from v_maiorData)																																																																																																				"
+ "AND Tipo_rac = 'Real'																																																																																																															"
+ "    AND [Tipo_Atendimento_rac] in (  'RECLAMAÇÃO',  'RECLAMAÇÃO ABUSO PROD.',  'RECLAMAÇÃO FAB. NÃO IDENTIF.',  'RECLAMAÇÃO HANS',  'CONTATO EXCELSIOR_RAC',  'CONTATO MERCADO DA CARNE',  'CONTATO JBS CARNES',  'NOTIFICAÇÃO',  'Reincidência',  'RECLAMAÇÃO FFO',  'RECLAMAÇÃO ABUSO DE PRODUTO',  'RECLAMAÇÃO VOSSKO',  'Reclamação Contas Globais'  )   AND Especialista_rac IN ('Igor', 'Rejane')   																		"
+ "GROUP BY [Mercado._rac], Tipo_Problema_rac, Nm_Manifestante_rac																																																																																																					"
+ "																																																																																																																					"
+ "																																																																																																																					"
+ "SELECT																																																																																																																			"
+ "Mercado																																																																																																																			"
+ ", SUM([Nº RAC]) [Nº RAC]																																																																																																															"
+ "INTO #Mercado																																																																																																																	"
+ "FROM #RESULTADO																																																																																																																	"
+ "GROUP BY Mercado																																																																																																																	"
+ "																																																																																																																					"
+ "SELECT																																																																																																																			"
+ "Mercado																																																																																																																			"
+ ", [Tipo do Problema]																																																																																																																"
+ ", SUM([Nº RAC]) [Nº RAC]																																																																																																															"
+ "INTO #TIPOPROBLEMA																																																																																																																"
+ "FROM #RESULTADO																																																																																																																	"
+ "GROUP BY Mercado, [Tipo do Problema]																																																																																																												"
+ "																																																																																																																					"
+ "SELECT																																																																																																																			"
+ "Mercado																																																																																																																			"
+ ", [Tipo do Problema]																																																																																																																"
+ ", [Manifestante]																																																																																																																	"
+ ", SUM([Nº RAC]) [Nº RAC]																																																																																																															"
+ "INTO #MANIFESTANTE																																																																																																																"
+ "FROM #RESULTADO																																																																																																																	"
+ "GROUP BY Mercado, [Tipo do Problema], [Manifestante]																																																																																																								"
+ "																																																																																																																					"
+ "SELECT																																																																																																																			"
+ "GROUPING(B.Mercado) U																																																																																																															"
+ ", GROUPING(B.[Tipo do Problema]) T																																																																																																												"
+ ", GROUPING(B.[Manifestante]) M																																																																																																													"
+ ", B.Mercado as Mercado1																																																																																																															"
+ ", B.[Tipo do Problema]																																																																																																															"
+ ", B.[Manifestante]																																																																																																																"
+ ", SUM([Nº RAC]) [Nº RAC]																																																																																																															"
+ "INTO #BASE																																																																																																																		"
+ "FROM #RESULTADO B																																																																																																																"
+ "GROUP BY Mercado, [Tipo do Problema], [Manifestante]																																																																																																								"
+ "WITH ROLLUP													  																																																																																																					"
+ "																																																																																																																					"
+ "																																																																																																																					"
+ "SELECT DISTINCT B.U, B.T, B.M, ISNULL(B.Mercado1,'Total') as Mercado1, ISNULL(B.[Tipo do Problema],'Total') as [Tipo do Problema], ISNULL(B.Manifestante,'Total') as Manifestante,																																																																								"
+ "b.[Nº RAC]																																																																																																																		"
+ ", U.[Nº RAC] Mercado_																																																																																																															"
+ ", T.[Nº RAC] TipoProblema_																																																																																																														"
+ ", M.[Nº RAC] Manifestante_																																																																																																														"
+ ", CASE																																																																																																																			"
+ "	WHEN B.[Manifestante] IS NULL THEN																																																																																																												"
+ "		CASE																																																																																																																		"
+ "			WHEN B.[Tipo do Problema] IS NULL THEN 																																																																																																									"
+ "                CASE 																																																																																																															"
+ "					WHEN B.Mercado1 IS NULL THEN																																																																																																									"
+ "					'<b>Total</b>'																																																																																																													"
+ "					ELSE '<b>'+B.Mercado1+'</b>'																																																																																																									"
+ "				END																																																																																																																	"
+ "			ELSE '@@.....'+B.[Tipo do Problema] 																																																																																																									"
+ "		END																																																																																																																			"
+ "	ELSE '..........'+B.[Manifestante]																																																																																																												"
+ "    END Mercado																																																																																																																	"
+ ", CASE																																																																																																																			"
+ "	WHEN B.[Manifestante] IS NULL THEN																																																																																																												"
+ "		CASE																																																																																																																		"
+ "			WHEN B.[Tipo do Problema] IS NULL THEN 																																																																																																									"
+ "                CASE 																																																																																																															"
+ "					WHEN B.Mercado1 IS NULL THEN																																																																																																									"
+ "					'Total'																																																																																																															"
+ "					ELSE B.Mercado1																																																																																																													"
+ "				END																																																																																																																	"
+ "			ELSE B.[Tipo do Problema] 																																																																																																												"
+ "		END																																																																																																																			"
+ "	ELSE B.[Manifestante]																																																																																																															"
+ "    END Mercado2																																																																																																																	"
+ "	INTO #NIVEIS																																																																																																																	"
+ "FROM #BASE B																																																																																																																		"
+ "LEFT JOIN #Mercado U ON B.Mercado1 = U.Mercado																																																																																																									"
+ "LEFT JOIN #TIPOPROBLEMA T ON B.Mercado1 = T.Mercado AND B.[Tipo do Problema] = T.[Tipo do Problema]																																																																																												"
+ "LEFT JOIN #MANIFESTANTE M ON B.Mercado1 = M.Mercado AND B.[Tipo do Problema] = M.[Tipo do Problema] AND B.[Manifestante] = M.[Manifestante]																																																																																		"
+ "																																																																																																																					"
+ "																																																																																																																					"
+ "ORDER BY 1, 8 DESC, 4, 2 DESC, 9 DESC, 5, 3 DESC, 10 DESC, 6																																																																																																						"
+ "																																																																																																																					"
+ "                                																																																																																																													"
+ "																																																																																																																					"
+ "																																																																																																																					"
+ "																																																																																																																					"
+ "             SELECT																																																																																																																"
+ "             [Mercado._rac] as Mercado																																																																																																											"
+ "             , Tipo_Problema_rac as [Tipo do Problema]																																																																																																							"
+ "             , Nm_Manifestante_rac as [Manifestante]																																																																																																								"
+ "             , sum(Quant_rac) Quant_rac																																																																																																											"
+ "             INTO #TOTAL																																																																																																															"
+ "             FROM [v_base_rac]																																																																																																													"
+ "             WHERE Mercado_rac = 'ME'																																																																																																											"
+ "            and year(data_rac) = (select year(data) as data from v_maiorData)																																																																																																	"
+ "            and month(data_rac) = (select month(data) as data from v_maiorData)																																																																																																	"
+ "            AND Tipo_rac = 'Real'																																																																																																												"
+ "            AND [Tipo_Atendimento_rac] in (  'RECLAMAÇÃO',  'RECLAMAÇÃO ABUSO PROD.',  'RECLAMAÇÃO FAB. NÃO IDENTIF.',  'RECLAMAÇÃO HANS',  'CONTATO EXCELSIOR_RAC',  'CONTATO MERCADO DA CARNE',  'CONTATO JBS CARNES',  'NOTIFICAÇÃO',  'Reincidência',  'RECLAMAÇÃO FFO',  'RECLAMAÇÃO ABUSO DE PRODUTO',  'RECLAMAÇÃO VOSSKO',  'Reclamação Contas Globais'  )   AND Especialista_rac IN ('Igor', 'Rejane')   																"
+ "            GROUP BY [Mercado._rac], Tipo_Problema_rac, Nm_Manifestante_rac																																																																																																		"
+ "             																																																																																																																	"
+ "             SELECT																																																																																																																"
+ "             'Total' as [Unidade],																																																																																																												"
+ "             sum(Quant_rac) Quant_rac																																																																																																											"
+ "             INTO #TOTALFINAL																																																																																																													"
+ "             FROM [v_base_rac]																																																																																																													"
+ "             WHERE Mercado_rac = 'ME'																																																																																																											"
+ "            and year(data_rac) = (select year(data) as data from v_maiorData)																																																																																																	"
+ "            and month(data_rac) = (select month(data) as data from v_maiorData)																																																																																																	"
+ "            AND Tipo_rac = 'Real'																																																																																																												"
+ "            AND [Tipo_Atendimento_rac] in (  'RECLAMAÇÃO',  'RECLAMAÇÃO ABUSO PROD.',  'RECLAMAÇÃO FAB. NÃO IDENTIF.',  'RECLAMAÇÃO HANS',  'CONTATO EXCELSIOR_RAC',  'CONTATO MERCADO DA CARNE',  'CONTATO JBS CARNES',  'NOTIFICAÇÃO',  'Reincidência',  'RECLAMAÇÃO FFO',  'RECLAMAÇÃO ABUSO DE PRODUTO',  'RECLAMAÇÃO VOSSKO',  'Reclamação Contas Globais'  )   AND Especialista_rac IN ('Igor', 'Rejane')   																"
+ "            GROUP BY [Mercado._rac], Tipo_Problema_rac, Nm_Manifestante_rac																																																																																																		"
+ "             																																																																																																																	"
+ "             SELECT																																																																																																																"
+ "             sum(Quant_rac) Quant_rac																																																																																																											"
+ "             INTO #TOTALF																																																																																																														"
+ "             FROM [v_base_rac]																																																																																																													"
+ "             WHERE Mercado_rac = 'ME'																																																																																																											"
+ "            and year(data_rac) = (select year(data) as data from v_maiorData)																																																																																																	"
+ "            and month(data_rac) = (select month(data) as data from v_maiorData)																																																																																																	"
+ "            AND Tipo_rac = 'Real'																																																																																																												"
+ "            AND [Tipo_Atendimento_rac] in (  'RECLAMAÇÃO',  'RECLAMAÇÃO ABUSO PROD.',  'RECLAMAÇÃO FAB. NÃO IDENTIF.',  'RECLAMAÇÃO HANS',  'CONTATO EXCELSIOR_RAC',  'CONTATO MERCADO DA CARNE',  'CONTATO JBS CARNES',  'NOTIFICAÇÃO',  'Reincidência',  'RECLAMAÇÃO FFO',  'RECLAMAÇÃO ABUSO DE PRODUTO',  'RECLAMAÇÃO VOSSKO',  'Reclamação Contas Globais'  )   AND Especialista_rac IN ('Igor', 'Rejane')   																"
+ "      																																																																																																																			"
+ "             																																																																																																																	"
+ "             																																																																																																																	"
+ "             DECLARE @SQLStr VARCHAR(max)																																																																																																										"
+ "             SET @SQLStr=''																																																																																																														"
+ "             																																																																																																																	"
+ "             SELECT																																																																																																																"
+ "             [MES-DIA] Descricao																																																																																																													"
+ "             INTO #TAB																																																																																																															"
+ "             FROM [v_base_rac]																																																																																																													"
+ "             																																																																																																																	"
+ "             WHERE Mercado_rac = 'ME'																																																																																																											"
+ "			 and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData)																																																																																	"
+ "			 AND Tipo_rac = 'Real'																																																																																																													"
+ "			 AND [Tipo_Atendimento_rac] in (  'RECLAMAÇÃO',  'RECLAMAÇÃO ABUSO PROD.',  'RECLAMAÇÃO FAB. NÃO IDENTIF.',  'RECLAMAÇÃO HANS',  'CONTATO EXCELSIOR_RAC',  'CONTATO MERCADO DA CARNE',  'CONTATO JBS CARNES',  'NOTIFICAÇÃO',  'Reincidência',  'RECLAMAÇÃO FFO',  'RECLAMAÇÃO ABUSO DE PRODUTO',  'RECLAMAÇÃO VOSSKO',  'Reclamação Contas Globais'  )   AND Especialista_rac IN ('Igor', 'Rejane')   																	"																									
+ "             GROUP BY [MES-DIA]																																																																																																													"
+ "             																																																																																																																	"
+ "             DECLARE @LINHAS INT 																																																																																																												"
+ "             																																																																																																																	"
+ "             SELECT @LINHAS = (SELECT COUNT(1) FROM #TAB)																																																																																																						"
+ "             																																																																																																																	"
+ "             DECLARE @Tabela TABLE (																																																																																																												"
+ "                 VALOR VARCHAR(MAX)																																																																																																												"
+ "             )																																																																																																																	"
+ "              																																																																																																																	"
+ "             INSERT @Tabela ( 																																																																																																													"
+ "                 VALOR																																																																																																															"
+ "             )																																																																																																																	"
+ "             SELECT  																																																																																																															"
+ "                 '||' 																																																																																																															"
+ "             FROM																																																																																																																"
+ "                 #TAB																																																																																																															"
+ "             GROUP BY 																																																																																																															"
+ "                 Descricao																																																																																																														"
+ "              																																																																																																																	"
+ "             DECLARE @Descricao VARCHAR(MAX)																																																																																																										"
+ "              																																																																																																																	"
+ "             DECLARE c CURSOR LOCAL FAST_FORWARD																																																																																																									"
+ "             FOR																																																																																																																	"
+ "              																																																																																																																	"
+ "                 SELECT  																																																																																																														"
+ "                     Descricao																																																																																																													"
+ "                 FROM																																																																																																															"
+ "                     #TAB																																																																																																														"
+ "                 ORDER BY 																																																																																																														"
+ "                     Descricao ASC																																																																																																												"
+ "              																																																																																																																	"
+ "              																																																																																																																	"
+ "             OPEN c																																																																																																																"
+ "              																																																																																																																	"
+ "             FETCH c INTO @Descricao																																																																																																												"
+ "              																																																																																																																	"
+ "             WHILE @@FETCH_STATUS = 0																																																																																																											"
+ "             BEGIN																																																																																																																"
+ "              																																																																																																																	"
+ "                 UPDATE  @Tabela																																																																																																													"
+ "                 SET     VALOR += ', [' + @Descricao + ']'																																																																																																						"
+ "              																																																																																																																	"
+ "                 FETCH c INTO @Descricao																																																																																																											"
+ "             END																																																																																																																	"
+ "              																																																																																																																	"
+ "             CLOSE c																																																																																																																"
+ "             DEALLOCATE c																																																																																																														"
+ "              																																																																																																																	"
+ "             SELECT  																																																																																																															"
+ "                 TOP 1 Descricoes = REPLACE(STUFF(VALOR, 1, 0, ''),'||,','')																																																																																																		"
+ "             INTO #TAB2																																																																																																															"
+ "             FROM																																																																																																																"
+ "                 @Tabela																																																																																																															"
+ "             																																																																																																																	"
+ "             SELECT @SQLStr = @SQLStr + (SELECT TOP 1 Descricoes FROM #TAB2)																																																																																																		"
+ "             																																																																																																																	"
+ "             DROP TABLE #TAB																																																																																																														"
+ "             DROP TABLE #TAB2																																																																																																													"
+ "             																																																																																																																	"
+ "             PRINT @SQLStr																																																																																																														"
+ "             SET @SQLStr = LEFT(@SQLStr,len(@SQLStr))																																																																																																							"
+ "																																																																																																																					"
+ "			 DECLARE @SQLStr1 VARCHAR(max)																																																																																																											"
+ "             SET @SQLStr1=''																																																																																																														"
+ "																																																																																																																					"
+ "             SET @SQLStr1 ='select * into #gabriel1 from ( SELECT pt.[Mercado], pt.[Tipo do Problema], pt.[Manifestante],   '																																																																																					"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT [Mercado._rac] as Mercado, Tipo_Problema_rac as [Tipo do Problema], Nm_Manifestante_rac as [Manifestante], [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																					"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																							
+ "             		' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		' +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [Mercado._rac], [Tipo_Problema_rac], [Nm_Manifestante_rac], [MES-DIA] '+      																																																																																									"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' INNER JOIN #TOTAL T ON T.[Mercado] = PT.[Mercado] AND T.[Tipo do Problema] = PT.[Tipo do Problema] AND T.[Manifestante] = PT.[Manifestante] ' +																																																																													"
+ "             																																																																																																																	"
+ "             ' UNION ALL ' +																																																																																																														"
+ "             ' SELECT pt.[Mercado], pt.[Tipo do Problema], pt.[Manifestante],   '																																																																																																"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT ''Total'' as Mercado, ''Total'' as [Tipo do Problema], ''Total''as [Manifestante],  [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																											"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																						          		
+ "					' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		'  +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [MES-DIA] '+      																																																																																																								"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' ) TT '																																																																																																															"
+ "																																																																																																																					"
+ "			 DECLARE @SQLStr2 VARCHAR(max)																																																																																																											"
+ "             SET @SQLStr2=''																																																																																																														"
+ "																																																																																																																					"
+ "             SET @SQLStr2 ='select * into #gabriel2 from ( SELECT pt.[Mercado], ''total'' as [Tipo do Problema], ''total'' as [Manifestante],   '																																																																																"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT [Mercado._rac] as Mercado, [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																																									"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																						
+ "             		' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		' +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [Mercado._rac], [MES-DIA] '+      																																																																																																				"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' INNER JOIN #TOTAL T ON T.[Mercado] = PT.[Mercado] ' +																																																																																																				"
+ "             																																																																																																																	"
+ "             ' UNION ALL ' +																																																																																																														"
+ "             ' SELECT pt.[Mercado], ''total'' as [Tipo do Problema], ''total'' as [Manifestante],   '																																																																																											"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT ''Total'' as Mercado,  [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																																										"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																						          		
+ "					' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		'  +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [MES-DIA] '+      																																																																																																								"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' ) TT '																																																																																																															"
+ "																																																																																																																					"
+ "			 DECLARE @SQLStr3 VARCHAR(max)																																																																																																											"
+ "             SET @SQLStr3=''																																																																																																														"
+ "																																																																																																																					"
+ "             SET @SQLStr3 ='select * into #gabriel3 from ( SELECT pt.[Mercado], pt.[Tipo do Problema], ''total'' as [Manifestante],   '																																																																																			"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT [Mercado._rac] as Mercado, Tipo_Problema_rac as [Tipo do Problema], [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																															"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																						
+ "             		' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		' +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [Mercado._rac], [Tipo_Problema_rac], [MES-DIA] '+      																																																																																															"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' INNER JOIN #TOTAL T ON T.[Mercado] = PT.[Mercado] AND T.[Tipo do Problema] = PT.[Tipo do Problema] ' +																																																																																							"
+ "             																																																																																																																	"
+ "             ' UNION ALL ' +																																																																																																														"
+ "             ' SELECT pt.[Mercado], pt.[Tipo do Problema], ''total'' as [Manifestante],   '																																																																																														"
+ "             + @SQLStr																																																																																																															"
+ "             + ' , 0 as Total ' +																																																																																																												"
+ "             + ' , 0 as Total2 ' +																																																																																																												"
+ "             + ' FROM (SELECT ''Total'' as Mercado, ''Total'' as [Tipo do Problema],  [MES-DIA] as [MES-DIA], sum(Quant_rac) Quant_rac  ' +																																																																																		"
+ "             '         from [v_base_rac] base with (nolock)  ' +																																																																																																					"
+ "             																																																																																																																	"
+ "             		' WHERE Mercado_rac = ''ME'' ' +																																																																																																							"
+ "                    ' AND [Tipo_Atendimento_rac] in (  ''RECLAMAÇÃO'',  ''RECLAMAÇÃO ABUSO PROD.'',  ''RECLAMAÇÃO FAB. NÃO IDENTIF.'',  ''RECLAMAÇÃO HANS'',  ''CONTATO EXCELSIOR_RAC'',  ''CONTATO MERCADO DA CARNE'',  ''CONTATO JBS CARNES'',  ''NOTIFICAÇÃO'',  ''Reincidência'',  ''RECLAMAÇÃO FFO'',  ''RECLAMAÇÃO ABUSO DE PRODUTO'',  ''RECLAMAÇÃO VOSSKO'',  ''Reclamação Contas Globais''  )   AND Especialista_rac IN (''Igor'', ''Rejane'')   '		+				"																						          		
+ "					' and year(data_rac) = (select year(data) as data from v_maiorData) and month(data_rac) = (select month(data) as data from v_maiorData) AND Tipo_rac = ''Real'' 		'  +																																																																					"
+ "             																																																																																																																	"
+ "                     ' GROUP BY [MES-DIA] '+      																																																																																																								"
+ "             '         ) sq PIVOT (sum(Quant_rac) FOR [MES-DIA] IN ('																																																																																																			"
+ "             + @SQLStr+')) AS pt ' +																																																																																																												"
+ "             ' ) TT '																																																																																																															"
+ "																																																																																																																					"
+ "			 SET @SQLStr = @SQLStr1 + ' ' + @SQLStr2 + ' ' + @SQLStr3 + ' ' + 																																																																																																		"
+ "																																																																																																																					"
+ "			 + ' SELECT * INTO #TTTT FROM  ((select * from #gabriel1) union all (select * from #gabriel2) union all (select * from #gabriel3)) FF  '																																																																																"
+ "																																																																																																																					"
+ "			 + ' SELECT distinct * FROM #NIVEIS N '																																																																																																									"
+ "			 + ' LEFT JOIN #TTTT T1 ON T1.Mercado = N.Mercado1 AND T1.[Tipo do Problema] = N.[Tipo do Problema] AND T1.Manifestante = N.Manifestante ' 																																																																																"
+ "			 + ' ORDER BY 1, 8 DESC, 4, 2 DESC, 9 DESC, 5, 3 DESC, 10 DESC, 6 '																																																																																																		"
+ "																																																																																																																					"
+ "             																																																																																																																	"
+ "             PRINT @SQLStr																																																																																																														"
+ "             EXEC(@SQLStr)																																																																																																														"
+ "			 																																																																																																																		"
+ "			 																																																																																																																		"
+ "             																																																																																																																	"
+ "             DROP TABLE #TOTAL																																																																																																													"
+ "             DROP TABLE #TOTALFINAL																																																																																																												"
+ "             DROP TABLE #TOTALF																																																																																																													"
+ "			 																																																																																																																		"
+ "			 DROP TABLE #RESULTADO																																																																																																													"
+ "            DROP TABLE #Mercado																																																																																																													"
+ "            DROP TABLE #TIPOPROBLEMA																																																																																																												"
+ "            DROP TABLE #MANIFESTANTE																																																																																																												"
+ "            DROP TABLE #BASE																																																																																																														"
+ "																																																																																																																					"
+ "			DROP TABLE #NIVEIS																																																																																																														"
];